### ISSUE TITLE
Not accessible from public IP / DDNS

### ISSUE THREAD

**Issue by Originaldoc** [chrisjohnson00/docker-qBittorrentvpn#43]
Hi @chrisjohnson00, 

I can access to qbittorrent webui from the local network and also if I set VPN_ENABLED=no, so turn off vpn service, but I can't get access from a public IP or DDNS service, I guess there is some iptables config missing.

I've never worked with iptables so I hope you could help me to solve it. Thank you!

This is my docker-compose.yml file:

> version: '3.4'
> services:
>   qbittorrent-openvpn:
>     image: chrisjohnson00/qbittorrent-openvpn:latest
>     container_name: qbittorrent-openvpn
>     privileged: true
>     restart: unless-stopped
>     volumes:
>       - ./downloads:/downloads
>       - ./config:/config
>     environment:
>       - VPN_ENABLED=yes
>       - LAN_NETWORK=192.168.1.0/24
>       - NAME_SERVERS=9.9.9.9,149.112.112.112
>       - VPN_USERNAME=xxxxxxxx
>       - VPN_PASSWORD=xxxxxxxx
>       - PUID=1000
>       - PGID=1000
>       - UMASK=002
>     ports:
>       - 8080:8080

**Comment by chrisjohnson00** [comment]
@Originaldoc - I forked this repo and added some additional automation for multi architecture docker builds.  The core of this I didn't create.
However, I don't think your issue is related to IP tables.
I got it setup on my network with VPN enabled, but I get "unauthorized"
When I look at the logs (inside the config dir) I get:

> (W) 2021-10-16T00:10:24 - WebUI: Invalid Host header, port mismatch. Request source IP: '::ffff:10.244.0.1'. Server port: '8080'. Received Host header: 'mydomain:30000'

My router is setup to forward port 30000 to my Kubernetes cluster, which has a node port service listening on 30000 and forwarding to the container on port 8080.


Once I disabled this setting:
![image](https://user-images.githubusercontent.com/1231933/137566237-03eee90f-dcdb-46c0-aa3c-b36623c5d9ba.png)

I was able to hit it externally without error.

Would you be able to check your logs and see what it says?
