### ISSUE TITLE
Upgrade Qbt source to 4.4 branch

### ISSUE THREAD

**Issue by inertia666** [chrisjohnson00/docker-qBittorrentvpn#58]
Any chance we will get 4.4.x branch? Thanks!

**Comment by chrisjohnson00** [comment]
I don't use this container anymore due to some issues I kept having with it losing VPN.
This is based on what's published to the Ubuntu repos, which you can see here: https://launchpad.net/~qbittorrent-team/+archive/ubuntu/qbittorrent-stable
Which looks like they don't support 4.4 on Ubuntu 20.04, which is what this container is based one.
I'd be happy to accept an update to the Dockerfile with it updated to 22.04, and verified to be working.  
I have no plans to continue to support this project, but won't kill it since it's fully automated on auto-pilot.

**Comment by chrisjohnson00** [comment]
@inertia666 Dependabot proposed an upgrade to Ubuntu 22.04, if you are willing to test this container and say it works, I'll promote this change
chrisjohnson00/qbittorrent-openvpn:dependabot-docker-ubuntu-22.04

FYI - docker hub will remove this tag if it's not used after a period of time, so if it's not there.  hollar and I'll re-run the automation that creates it.

**Comment by chrisjohnson00** [comment]
I just rebuilt the Ubuntu 22.04 container, and it is running version `4.5.5`.  
Again, if the container isn't pulled, Docker Hub will delete it after some time (30 days, 60 days??)
If anyone uses this, pls comment if it is working and I'll do the upgrade to apply this going forward via the `latest` tag.

**Comment by chrisjohnson00** [comment]
Fixed by: https://github.com/chrisjohnson00/docker-qBittorrentvpn/pull/111
